version: "2"

run:
  timeout: 3m

linters:
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - govet
    - ineffassign
    - nilerr
    - unconvert
    - unparam
    - unused
    - staticcheck
    - wastedassign
  exclusions:
    paths:
      - shared/gen
