ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS prompt_tokens      INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS completion_tokens   INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS tokens_per_second   DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS model               TEXT NOT NULL DEFAULT '' CHECK (char_length(model) <= 255);
