from prometheus_client import Counter, Histogram, Gauge

ai_requests_total = Counter(
    "ai_requests_total",
    "Total inference requests",
    ["execution_status", "task_type"],
)

ai_request_duration_seconds = Histogram(
    "ai_request_duration_seconds",
    "Total request duration including graph execution",
    ["task_type"],
    buckets=[0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)

ai_inference_duration_seconds = Histogram(
    "ai_inference_duration_seconds",
    "Ollama inference duration",
    ["model"],
    buckets=[0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)

ai_inference_in_flight = Gauge(
    "ai_inference_in_flight",
    "Number of Ollama inference calls currently in progress",
)

ai_validation_status_total = Counter(
    "ai_validation_status_total",
    "Output validation outcomes",
    ["validation_status"],
)

ai_failures_total = Counter(
    "ai_failures_total",
    "Inference failures by reason",
    ["reason"],
)

ai_output_chars = Histogram(
    "ai_output_chars",
    "Output size in characters",
    ["model", "truncated"],
    buckets=[100, 500, 1000, 2000, 4000, 8000],
)

llm_prompt_tokens_total = Counter(
    "traceruntime_llm_prompt_tokens_total",
    "Cumulative prompt tokens sent to LLM",
    ["model", "task_type"],
)

llm_completion_tokens_total = Counter(
    "traceruntime_llm_completion_tokens_total",
    "Cumulative completion tokens generated by LLM",
    ["model", "task_type"],
)

llm_tokens_total = Counter(
    "traceruntime_llm_tokens_total",
    "Cumulative total tokens (prompt + completion)",
    ["model", "task_type"],
)

llm_output_tokens = Histogram(
    "traceruntime_llm_output_tokens",
    "Distribution of output token counts per inference",
    ["model", "task_type"],
    buckets=[50, 100, 250, 500, 1000, 2000, 4000],
)

llm_inference_tokens_per_second = Histogram(
    "traceruntime_llm_inference_tokens_per_second",
    "Inference speed in completion tokens per second",
    ["model", "task_type"],
    buckets=[1, 5, 10, 20, 40, 80, 160, 320],
)
